#!/usr/bin/env python3
"""bank.json (display units) -> src/dsp/hank_presets.h (engine units).

Build-time step. Nothing parses JSON on the device: the bank lands as a static
C table, which is what keeps preset loading off the SPI callback.
"""
import json, os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
bank = json.load(open(os.path.join(HERE, "bank.json")))
d = bank["_defaults"]
FIELDS = [
    ("ratio",      "ratio",      lambda v: v),
    ("bright",     "bright",     lambda v: v),
    ("bite",       "bite",       lambda v: v),
    ("tone",       "tone",       lambda v: v),
    ("attack",     "attack",     lambda v: v),
    ("decay",      "decay",      lambda v: v),
    ("sustain",    "sustain",    lambda v: v),
    ("noise",      "noise",      lambda v: v),
    ("macro_mode", "macro_mode", lambda v: float(v)),
    ("voice_count","voices",     lambda v: float(v)),
    ("glide",      "glide",      lambda v: v/100.0),
    ("pitch",      "pitch",      lambda v: float(v)),
    ("crush",      "crush",      lambda v: v/100.0),
    ("keytrack",   "keytrack",   lambda v: float(v)),
    ("volume",     "volume",     lambda v: v/100.0),
    # Level calibration, fitted against a five-note chord -- see Params.
    # It is deliberately NOT `volume`: that is the player's trim and is live
    # state, so calibrating with it made the knob mean something different on
    # every preset and let a slot keep an old level forever.
    ("preset_gain","gain",        lambda v: v),
]
def cfloat(v):
    t = "%g" % v
    if "e" in t or "E" in t: t = "%.9g" % v
    if "." not in t and "e" not in t and "E" not in t: t += ".0"
    return t + "f"

out = ["/* GENERATED by presets/gen_presets.py from presets/bank.json -- do not edit. */",
       "#ifndef HANK_PRESETS_H", "#define HANK_PRESETS_H", "",
       "namespace hank {", "",
       "struct PresetDef { const char *name; const char *cat; float v[%d]; };" % len(FIELDS), ""]
# A PRESET MAY ONLY USE WHAT THE PLAYER CAN REACH. The eight macros, plus the
# Setup page. Nothing from the Tune pages: those are raw engine values that
# applyMacros overwrites unless Macros is switched off, so a preset depending on
# one would be a patch the player could never recreate or edit.
_MACROS = {"ratio","bright","bite","tone","attack","decay","sustain","noise"}
_SETUP  = {"voices","glide","pitch","volume","gain"}
for _p in bank["presets"]:
    _bad = set(_p) - _MACROS - _SETUP - {"name","cat"}
    if _bad:
        raise SystemExit(f"preset {_p['name']!r} uses unreachable params: {sorted(_bad)}")

rows = []
for p in bank["presets"]:
    vals = []
    for _, key, conv in FIELDS:
        vals.append(conv(p.get(key, d[key])))
    rows.append('    { "%s", "%s", { %s } }' % (p["name"], p["cat"],
                ", ".join(cfloat(v) for v in vals)))
out.append("static const PresetDef HANK_PRESETS[] = {")
out.append(",\n".join(rows))
out.append("};")
out.append("static const int HANK_PRESET_COUNT = %d;" % len(rows))
out.append("")
out.append("/* field order, matching PresetDef::v -- consumed by applyPreset() */")
out.append("enum PresetField {")
for i,(name,_,_) in enumerate(FIELDS):
    out.append("    PF_%s = %d," % (name.upper(), i))
out.append("    PF_COUNT = %d" % len(FIELDS))
out.append("};")
out.append("")
out.append("} /* namespace hank */")
out.append("#endif")
dst = os.path.join(HERE, "..", "src", "dsp", "hank_presets.h")
open(dst, "w").write("\n".join(out) + "\n")
print("wrote %s (%d presets, %d fields)" % (dst, len(rows), len(FIELDS)))
